alertmanager:
  config:
    global:
      smtp_smarthost: host.docker.internal:1025
      smtp_from: alerts@local.dev

    route:
      receiver: mailhog
      group_wait: 5s
      group_interval: 5s
      repeat_interval: 30s

    receivers:
    - name: mailhog
      email_configs:
      - to: you@local.dev
        send_resolved: true
